### ISSUE TITLE
support multiarch build in dockerhub

### ISSUE THREAD

**Issue by danielecr** [danielecr/uuid-provider#1]
just seen
https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/
add
```yaml
name: build our image

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: build the image
      run: |
        docker buildx build \
          --tag your-username/multiarch-example:latest \
          --platform linux/amd64,linux/arm/v7,linux/arm64 .
```
in .github/workflows/image.yml to build multiarch

with https://github.com/marketplace/actions/docker-buildx github action ...what is that? action? ok, let's see
